# Generated by Django 5.2.7 on 2025-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_release_date_game_release_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_dates',
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
